name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["8.1", "8.2", "8.3"]
                symfony: ["^5.4", "^6.4", "^7.4"]
                exclude:
                    -   php: "8.1"
                        symfony: "^7.4"

        steps:
            -   uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global config --no-plugins allow-plugins.symfony/flex true
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^2.4"
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -   name: Install dependencies
                run: composer update

            -   name: Run analysis
                run: composer validate --strict

            -   name: Run tests
                run: vendor/bin/behat --strict -vvv --no-interaction

    unstable:
        runs-on: ubuntu-latest
        name: "Unstable - PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}"
        needs: tests
        strategy:
            fail-fast: false
            matrix:
                php: ["8.2", "8.3", "8.4"]
                symfony: ["^7.4"]
                include:
                    -   php: "8.4"
                        symfony: "^8.0"

        steps:
            -   uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global config --no-plugins allow-plugins.symfony/flex true
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^2.4"
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -   name: Install dependencies
                run: |
                    composer require behat/behat:"4.x-dev as 3.99" --no-install
                    composer update

            -   name: Run tests
                run: vendor/bin/behat --strict -vvv --no-interaction
                continue-on-error: true
